name: Docker Image CI

on:
  push:
    branches:
      - "ci-docker"

  pull_request:
    branches: 
      - "develop"

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Prepare .env file
      run: echo > .env
    - name: Build the project
      run: docker-compose build
