name: Docker Image CI

on:
  push:
    branches:
      - "ci-docker"

  pull_request:
    branches: 
      - "develop"

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - run: which docker-compose
    - run: docker-compose -v
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the frontend image
      run: cd web && docker build . --file Dockerfile
    - name: Build the backend image
      run: cd back && docker build . --file Dockerfile
